In [22]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [17]:
a = tf.constant((2, 3), shape=(1, 2))
a

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[2, 3]])>

In [25]:
a = (10, 11)
tf.convert_to_tensor(3, dtype=tf.float16)

<tf.Tensor: shape=(), dtype=float16, numpy=3.0>

In [29]:
np.random.seed(10)
a = np.random.randint(10, 50, 12).reshape(4, 3)
a

array([[19, 46, 25],
       [10, 38, 35],
       [39, 39, 18],
       [19, 10, 46]])

In [30]:
tf.reduce_max(a, axis=1)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([46, 38, 39, 46])>

In [31]:
tf.reduce_prod(a, axis=1)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([21850, 13300, 27378,  8740])>

In [33]:
tf.multiply([1, 2], [2, 3])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 6])>

In [34]:
tf.pow(2, 3)

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [37]:
tf.abs([-2, 5])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5])>

In [39]:
tf.acos(1/2)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0471976>

In [40]:
np.pi/3

1.0471975511965976

In [52]:
a = [10, 12, 13]
b = [1, 0, 2]
c = tf.data.Dataset.from_tensor_slices((a, b))
for a, b in c:
    print(a, b)

tf.Tensor(10, shape=(), dtype=int32) tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32) tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(13, shape=(), dtype=int32) tf.Tensor(2, shape=(), dtype=int32)


In [53]:
dot = pd.read_csv("D:/JetBrains/PyCharm2021.3.2/WorkSpace/PK-Tensorflow/class2/dot.csv")
dot.head()

x1        x2  y_c
0 -0.416758 -0.056267    1
1 -2.136196  1.640271    0
2 -1.793436 -0.841747    0
3  0.502881 -1.245288    1
4 -1.057952 -0.909008    1

In [54]:
tf.constant([2, 3]) + 2

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 5])>